src/beans/Order.java
/*
 * Author: Donald Trowbridge
 * Date: 11/20/2020
 * Class: CST235-O500
 * Statement: This work is my own.
 * Late Update:
 * Notes:
 * 	- 11/20/2020 : Object for a order object
 */
package beans;

public class Order {

	protected String orderNumber, productName;
	protected Float price;
	protected int quantity;
	
	/*
	 * Default constructor
	 */
	public Order() {
		this.price = 0F;
		this.quantity = 0;
	}
	
	/*
	 * Construct to fill out order details
	 */
	public Order(String orderNumber, String productName, Float price, int quantity) {
		this.orderNumber = orderNumber;
		this.productName = productName;
		this.price = price;
		this.quantity = quantity;
	}
	
	public String getOrderNumber() {
		return orderNumber;
	}
	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public Float getPrice() {
		return price;
	}
	public void setPrice(Float price) {
		this.price = price;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
	
}

src/beans/Orders.java
/*
 * Author: Donald Trowbridge
 * Date: 11/20/2020
 * Class: CST235-O500
 * Statement: This work is my own.
 * Late Update:
 * Notes:
 * 	- 11/20/2020 : Holds orders for user
 */

package beans;
import java.util.List;
import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


@ManagedBean
@ViewScoped
public class Orders {
	protected List<Order> orders = new ArrayList<Order>();
	
	public Orders() {
		/*
		 * Test data for orders response page
		 */
		orders.add(new Order("7692363895", "Samsung 1TB SSD", 199.99F, 2));
		orders.add(new Order("6298638572", "Raspberry Pi 4", 49.99F, 1));
		orders.add(new Order("6298638572", "Raspberry Pi 4 Case", 15.00F, 1));
		orders.add(new Order("6298638572", "Raspberry Pi 4 Screen", 34.99F, 1));
		orders.add(new Order("4507693749", "Nitendo Switch 32 GB Console", 441.00F, 1));
		orders.add(new Order("4507693749", "Nitendo Joy-Con", 69.00F, 2));
		orders.add(new Order("4507693749", "Mario Kart 8 Deluxe", 44.99F, 1));
		orders.add(new Order("4507693749", "Mario + Rabbids Kingdom Battle", 26.99F, 1));
		orders.add(new Order("3720365683", "SanDisk Cruzer 32GB Flash Drive", 19.99F, 5));
		orders.add(new Order("7692363895", "Security Testing With Raspberry Pi", 22.00F, 1));
	}
	
	public List<Order> getOrders() {
		return orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}
	
}

src/beans/User.java
/*
 * Author: Donald Trowbridge
 * Date: 11/13/2020
 * Class: CST235-O500
 * Statement: This work is my own.
 * Late Update: 11/20/2020
 * Notes:
 * 	- 11/20/2020 : Added annotations of data validation
 */

package beans;
import javax.faces.bean.ViewScoped;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.faces.bean.ManagedBean;


@ManagedBean(name="User")
@ViewScoped
public class User{

	@NotNull
	@Size(min=5, max=15)
	protected String firstName;
	protected String lastName;
	
	@NotNull
	@Size(min=5, max=15)
	public User() {
		firstName = "Donald";
		lastName = "Trowbridge";
	}
	
	public String getFirstName() {
		return this.firstName;
	}
	
	public String getLastName() { 
		return this.lastName;
	}
	
	public void setFirstName(String firstname) {
		firstName = firstname;
	}
	
	public void setLastName(String lastname) {
		lastName = lastname;
	}
}

src/controllers/FormController.java
/*
  Author: Donald Trowbridge
  Date: 11/14/2020
  Class: CST235-O500
  Statement: This work is my own.
  Last Update: 12/1/2020
  Notes:
  	-11/24/2020 : Injected OrdersBusinessInterface, add MyTimerService. Orders are now retrieved from the 
  				instantiated session bean corresponding to the OrdersBusinessInterface, and a timer is set to display a message after 10 seconds.
  	-12/1/2020  : Added methods to query database to pull all products and to add a product.
*/

package controllers;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import beans.User;
import business.OrdersBusinessInterface;
import business.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.ejb.EJB;


import javax.inject.Inject;

@ManagedBean(name="formController")
@ViewScoped

public class FormController {
	
	@Inject private OrdersBusinessInterface services;
	@EJB MyTimerService timer;
	
	public String onSubmit(User user) {
		FacesContext context = FacesContext.getCurrentInstance();
		context.getExternalContext().getRequestMap().put("User", user);
		services.test();
		timer.setTimer(10000);
		getAllOrders();
		insertOrder();
		getAllOrders();
		return "TestResponse.xhtml";
	}
	
	public String onFlash(User user) {
		FacesContext context = FacesContext.getCurrentInstance();
		context.getExternalContext().getFlash().put("User", user);
		return "TestResponse2.xhtml?faces-redirect=true";
	}
	
	public OrdersBusinessInterface getService(){
		return services;
	}
	
	/*
	 * Queries all orders from the orders table
	 */
	private void getAllOrders() {
		Connection conn = null;
		String query = "select * from testapp.orders";
		try {
			conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "admin");
			Statement statement = conn.createStatement();
			ResultSet resultSet = statement.executeQuery(query);
			System.out.println("ID\tProduct_Name\t\tPrice");
			while(resultSet.next()) {
				System.out.printf("%d\t%s\t$%.2f\n", resultSet.getInt("id"), resultSet.getString("product_name"), resultSet.getFloat("price"));
			}
			resultSet.close();
			System.out.println("Success!!");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("Failure!!");
		}finally {
			if(conn != null) {
				try {
					conn.close();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
	}
	
	/*
	 * Inserts an product into the orders database.
	 */
	private void insertOrder() {
		Connection conn = null;
		String insertQuery = "insert into testapp.orders(ORDER_NO, PRODUCT_NAME, PRICE, QUANTITY) VALUES('001122334455', 'This was inserted new', 25.00, 100)";
		try {
			conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "admin");
			Statement statement = conn.createStatement();
			statement.executeUpdate(insertQuery);
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			if(conn != null) {
				try{
					conn.close();
				} catch(SQLException e) {
					e.printStackTrace();
				}
			}
		}
	}
}

WebContent/TestForm.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/13/2020
  Class: CST235-O500
  Statement: This work is my own.
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>JSF Form Page</title>
</h:head> 
<body> 
<ui:composition template="/layouts/commonLayout.xhtml">
	<ui:define name="content">
		<h:form>
				<h:outputLabel for="firstname">First Name: </h:outputLabel>
				<h:inputText id="firstname" value="#{User.firstName}" />
				<br />
				<h:outputLabel for="lastname">Last Name: </h:outputLabel>
				<h:inputText for="lastname" value="#{User.lastName}" label="Last Name:"/>
				<br />
				<h:commandButton action="#{formController.onSubmit(User)}" value="Submit" />
				<h:commandButton action="#{formController.onFlash(User)}" value="Flash" />
		</h:form>
		<h:messages />
	</ui:define>
</ui:composition>
</body> 
</html>

WebContent/TestResponse.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/13/2020
  Class: CST235-O500
  Statement: This work is my own.
  Last Update: 11/20/2020
  Notes:
  	-11/20/2020 : Added code for data table and changed output to display new message
  	-11/24/2020 : DataTable updated to pull list of orders from FormController.services
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>JSF Response Page</title>
</h:head> 
<body> 
	<!-- Imports template to web page -->
	<ui:composition template="/layouts/commonLayout.xhtml">
		<!-- Define the content of the web page -->
		<ui:define name="content">
			<h:outputText value="Hello #{User.firstName} #{User.lastName}. Your orders are:"/>
			<br />
			<br />
			
			<!-- Creates data table of orders -->
						<h:dataTable value="#{formController.service.orders}" var="order">
				<h:column>
					<f:facet name="header">Order Number</f:facet>
					#{order.orderNumber}
				</h:column>
				<h:column>
					<f:facet name="header">Product Number</f:facet>
					#{order.productName}
				</h:column>
				<h:column>
					<f:facet name="header">Price</f:facet>
					$#{order.price}
				</h:column>
				<h:column>
					<f:facet name="header">Quantity</f:facet>
					#{order.quantity}
				</h:column>
			</h:dataTable>
			<br />
			<h:button value="back" outcome="TestForm.jsf" />
		</ui:define>
	</ui:composition>
</body> 
</html>

WebContent/TestResponse2.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/14/2020
  Class: CST235-O500
  Statement: This work is my own.
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>JSF Response Page</title>
</h:head> 
<body> 
	<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="content">
			<label>First Name: </label>
			<h:outputText id="firstname" value="#{flash.User.firstName}"/>
			<br />
			<label>Last Name: </label>
			<h:outputText id="lastname" value="#{flash.User.lastName}" />
			<br />
			<h:button value="back" outcome="TestForm.jsf" />
		</ui:define>
	</ui:composition>
</body> 
</html>

WebContent/layouts/commonContent.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/13/2020
  Class: CST235-O500
  Statement: This work is my own.
  Last Update:
  Notes:
  	-11/20/2020 : Template for the content in the page layout. This page is considered complete
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

<ui:composition>
</ui:composition>
</html>

WebContent/layouts/commonFooter.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/13/2020
  Class: CST235-O500
  Statement: This work is my own.
  Last Update:
  Notes:
  	-11/20/2020 : Template for the footer in the page layout. This page is considered complete
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">


<ui:composition>
	<h5 style="text-align: center;">@Copyright Grand Canyon University</h5>
</ui:composition>

</html>

WebContent/layouts/commonHeader.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/13/2020
  Class: CST235-O500
  Statement: This work is my own.
  Last Update:
  Notes:
  	-11/20/2020 : Template for the header in the page layout. This page is considered complete
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
<ui:composition>
	<h1 style="text-align: center">GCU In-Class Activity</h1>
</ui:composition>
</html>

WebContent/layouts/commonLayout.xhtml
<!--
  Author: Donald Trowbridge
  Date: 11/13/2020
  Class: CST235-O500
  Statement: This work is my own.
  Last Update:
  Notes:
  	-11/20/2020 : Template for the page layout.
 -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<h:outputStylesheet library="css" name="style.css" target="head"></h:outputStylesheet>
</h:head> 
<body>
	<!-- inserts the partial components of the page into this standard page layout -->
	<ui:insert name="header">
		<ui:include src="/layouts/commonHeader.xhtml"></ui:include>
	</ui:insert>
	<ui:insert name="content">
		<ui:include src="layouts/commonContent.xhtml"></ui:include>
	</ui:insert>
	<ui:insert name="footer">
		<ui:include src="/layouts/commonFooter.xhtml"></ui:include>
	</ui:insert>
</body>
</html>